# How long, in seconds between announcements.
interval: 300

# Make multiple-line announcements by using \n to begin a new line.
# Full color-codes are supported.

announcements:
  - "&7Thanks for installing &cAutoBroadcast&7!"
  - "&7Make sure to &cadd &7and &cconfigure&7 broadcasts in the config.yml file!"
  - "&7You can add an &cunlimited&7 amount of broadcasts."
  - "&cHere&7 is an \nexample of a \nmultiple-line message."