name: AutoBroadcast
version: ${project.version}
main: co.paradaux.hibernia.AutoBroadcast.AutoBroadcast
api-version: 1.13
authors: [Paradaux]
description: Simple utility plugin to send messages at a set interval. 
